### ISSUE TITLE
Pause/Resume

### ISSUE THREAD

**Issue by boriscosic** [ConnorDoyle/jquery.polartimer.js#1]
Thanks for the great code. I've added the ability to resume and pause the timer.

pause : function () {
            return this.each(function () {
                var data = $(this).data('polartimer');
                if (data) {
                    clearInterval(data.timer);
                }
            });
        },

resume : function (seconds_left) {
            return this.each(function () {
                var data = $(this).data('polartimer');
                if (data) {
                    clearInterval(data.timer);
                    data.timerFinish = new Date().getTime()+(seconds_left*1000);
                    $(this).polartimer('drawTimer', 0);
                    data.timer = setInterval("$this.polartimer('stopWatch')", 50);
                }
            });
        },

**Comment by ConnorDoyle** [comment]
Thanks Boris, I will run some tests and then roll these methods into the repo as well as the live demo page.  I will add a credit to you in the README file.  I'm glad you found this useful.  I should get to this tomorrow.

**Comment by ConnorDoyle** [comment]
Added, tested, cleaned up a bit, and updated the docs on the project page.  Thanks again.  Wow, didn't get to that nearly as quick as I thought I would :)
