### ISSUE TITLE
Using two timers on one page

### ISSUE THREAD

**Issue by creativekidney** [ConnorDoyle/jquery.polartimer.js#2]
Hi there,

thanks for making this timer, it looks great and has exactly the functionality I need.

I'm just writing to ask if it's possible to add two timers to one page?

I hope there is a way to do this because I've spent hours implementing your timer properly, and I'm not sure what I'll use without it!

Thanks,
Luke.

**Comment by ConnorDoyle** [comment]
Hi luke, cool project you've got there!

Sure enough, the plugin was struggling with multiple timers.  I just committed some changes that hopefully fix the issue.

If there is no id attribute on the element you invoke the plugin on, it behaves as before.  To run multiple timers, make sure you put an id attribute on each one.

I will post a minified version and update the docs shortly.  To see the latest in action, go to: http://oneorangesoftware.com/polartimer/twotimers.html

Probably, it would be more efficient to have just one timer invoking the animation for all of the polartimer instances.  If you have just a few it should do fine for the time being.  I'll create an issue to that effect as well.

## Thanks!

Connor

**Comment by ConnorDoyle** [comment]
Alright, the demo and docs are all updated.  I also updated the demo to use more recent versions of jQuery and Raphael.  I'd be interested to know if this helps you out, or if this is still an issue.

**Comment by creativekidney** [comment]
Thanks. It's my final year uni project, so putting everything I've got into it!

I re-downloaded the code, and changed a little of my code, and it's now all working brilliantly.

Thanks a lot for the quick reply, the timers look awesome =)

**Comment by piratdavid** [comment]
Fork for Snap SVG library pushed.

**Comment by ConnorDoyle** [comment]
@piratdavid Would you mind submitting a pull request for this?

**Comment by piratdavid** [comment]
@ConnorDoyle Created a pull request.
